//------------------------------------------------------------------------------
// <copyright file="SmsSendShortMessageDTO.cs">
//    Copyright (c) 2018, All rights reserved.
// </copyright>
// <author>YuanRui</author>
// <date>2018-08-24 17:06:25</date>
// <auto-generated>
//    This code was generated by Banana.AutoCode.exe
//    Template Version:20180824
//    Runtime Version:4.0.30319.42000
//
//    Changes to this file may cause incorrect behavior and will be lost if
//    the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banana.RPC
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.IO;
    using System.Text;
    using Banana.Entity;

    public partial class SmsSendShortMessageDTO
    {
        public static implicit operator SmsSendShortMessageEntity(SmsSendShortMessageDTO dto)
        {
            if (dto == null)
            {
                return default(SmsSendShortMessageEntity);
            }

            var ent = new SmsSendShortMessageEntity();
            ent.ID = dto.ID;
	        ent.CATEGORY = dto.CATEGORY;
	        ent.STATUS = dto.STATUS;
	        ent.PHONE = dto.PHONE;
	        ent.CONTENT = dto.CONTENT;
	        ent.SENT_AT = dto.SENT_AT;
	        ent.RESULT = dto.RESULT;
	        ent.CONTACT = dto.CONTACT;
	        ent.MODEM_ID = dto.MODEM_ID;
	        ent.SENT_COUNT = dto.SENT_COUNT;
	        ent.PLATE_NUMBER = dto.PLATE_NUMBER;
	        ent.PLATE_COLOR = dto.PLATE_COLOR;
	        ent.PECCANCY_TYPE = dto.PECCANCY_TYPE;
	        ent.TERMINAL_CODE = dto.TERMINAL_CODE;
	        ent.EVENT_CODE = dto.EVENT_CODE;
	        ent.FILE_PATH = dto.FILE_PATH;
	        ent.REQUEST_AT = dto.REQUEST_AT;
	        ent.CREATED_AT = dto.CREATED_AT;
	        ent.REMARK = dto.REMARK;
	        ent.IMG_INFO = dto.IMG_INFO;
	        ent.ENTITY_ID = dto.ENTITY_ID;
	        ent.SMS_COUNT = dto.SMS_COUNT;
	        ent.SURPLUS_COUNT = dto.SURPLUS_COUNT;
	        ent.SEND_STATE = dto.SEND_STATE;
	        ent.CREATED_BY = dto.CREATED_BY;
	
            return ent;
        }

        public static implicit operator SmsSendShortMessageDTO(SmsSendShortMessageEntity ent)
        {
            if(ent == null)
            {
                return default(SmsSendShortMessageDTO);
            }
            
            var dto = new SmsSendShortMessageDTO();
            dto.ID = ent.ID;
	        dto.CATEGORY = ent.CATEGORY;
	        dto.STATUS = ent.STATUS;
	        dto.PHONE = ent.PHONE;
	        dto.CONTENT = ent.CONTENT;
	        dto.SENT_AT = ent.SENT_AT;
	        dto.RESULT = ent.RESULT;
	        dto.CONTACT = ent.CONTACT;
	        dto.MODEM_ID = ent.MODEM_ID;
	        dto.SENT_COUNT = ent.SENT_COUNT;
	        dto.PLATE_NUMBER = ent.PLATE_NUMBER;
	        dto.PLATE_COLOR = ent.PLATE_COLOR;
	        dto.PECCANCY_TYPE = ent.PECCANCY_TYPE;
	        dto.TERMINAL_CODE = ent.TERMINAL_CODE;
	        dto.EVENT_CODE = ent.EVENT_CODE;
	        dto.FILE_PATH = ent.FILE_PATH;
	        dto.REQUEST_AT = ent.REQUEST_AT;
	        dto.CREATED_AT = ent.CREATED_AT;
	        dto.REMARK = ent.REMARK;
	        dto.IMG_INFO = ent.IMG_INFO;
	        dto.ENTITY_ID = ent.ENTITY_ID;
	        dto.SMS_COUNT = ent.SMS_COUNT;
	        dto.SURPLUS_COUNT = ent.SURPLUS_COUNT;
	        dto.SEND_STATE = ent.SEND_STATE;
	        dto.CREATED_BY = ent.CREATED_BY;
	
            return dto;
        }
    }
}
