/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Apache.Hadoop.Hbase.Thrift2
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TAppend : TBase
  {
    private Dictionary<byte[], byte[]> _attributes;
    private TDurability _durability;
    private TCellVisibility _cellVisibility;

    public byte[] Row { get; set; }

    public List<TColumnValue> Columns { get; set; }

    public Dictionary<byte[], byte[]> Attributes
    {
      get
      {
        return _attributes;
      }
      set
      {
        __isset.attributes = true;
        this._attributes = value;
      }
    }

    /// <summary>
    /// 
    /// <seealso cref="TDurability"/>
    /// </summary>
    public TDurability Durability
    {
      get
      {
        return _durability;
      }
      set
      {
        __isset.durability = true;
        this._durability = value;
      }
    }

    public TCellVisibility CellVisibility
    {
      get
      {
        return _cellVisibility;
      }
      set
      {
        __isset.cellVisibility = true;
        this._cellVisibility = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool attributes;
      public bool durability;
      public bool cellVisibility;
    }

    public TAppend() {
    }

    public TAppend(byte[] row, List<TColumnValue> columns) : this() {
      this.Row = row;
      this.Columns = columns;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_row = false;
        bool isset_columns = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Row = iprot.ReadBinary();
                isset_row = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.List) {
                {
                  Columns = new List<TColumnValue>();
                  TList _list44 = iprot.ReadListBegin();
                  for( int _i45 = 0; _i45 < _list44.Count; ++_i45)
                  {
                    TColumnValue _elem46;
                    _elem46 = new TColumnValue();
                    _elem46.Read(iprot);
                    Columns.Add(_elem46);
                  }
                  iprot.ReadListEnd();
                }
                isset_columns = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Map) {
                {
                  Attributes = new Dictionary<byte[], byte[]>();
                  TMap _map47 = iprot.ReadMapBegin();
                  for( int _i48 = 0; _i48 < _map47.Count; ++_i48)
                  {
                    byte[] _key49;
                    byte[] _val50;
                    _key49 = iprot.ReadBinary();
                    _val50 = iprot.ReadBinary();
                    Attributes[_key49] = _val50;
                  }
                  iprot.ReadMapEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I32) {
                Durability = (TDurability)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.Struct) {
                CellVisibility = new TCellVisibility();
                CellVisibility.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_row)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Row not set");
        if (!isset_columns)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Columns not set");
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TAppend");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Row == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Row not set");
        field.Name = "row";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Row);
        oprot.WriteFieldEnd();
        if (Columns == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Columns not set");
        field.Name = "columns";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Columns.Count));
          foreach (TColumnValue _iter51 in Columns)
          {
            _iter51.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
        if (Attributes != null && __isset.attributes) {
          field.Name = "attributes";
          field.Type = TType.Map;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteMapBegin(new TMap(TType.String, TType.String, Attributes.Count));
            foreach (byte[] _iter52 in Attributes.Keys)
            {
              oprot.WriteBinary(_iter52);
              oprot.WriteBinary(Attributes[_iter52]);
            }
            oprot.WriteMapEnd();
          }
          oprot.WriteFieldEnd();
        }
        if (__isset.durability) {
          field.Name = "durability";
          field.Type = TType.I32;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)Durability);
          oprot.WriteFieldEnd();
        }
        if (CellVisibility != null && __isset.cellVisibility) {
          field.Name = "cellVisibility";
          field.Type = TType.Struct;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          CellVisibility.Write(oprot);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TAppend(");
      __sb.Append(", Row: ");
      __sb.Append(Row);
      __sb.Append(", Columns: ");
      __sb.Append(Columns);
      if (Attributes != null && __isset.attributes) {
        __sb.Append(", Attributes: ");
        __sb.Append(Attributes);
      }
      if (__isset.durability) {
        __sb.Append(", Durability: ");
        __sb.Append(Durability);
      }
      if (CellVisibility != null && __isset.cellVisibility) {
        __sb.Append(", CellVisibility: ");
        __sb.Append(CellVisibility== null ? "<null>" : CellVisibility.ToString());
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
