/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Apache.Hadoop.Hbase.Thrift2
{

  /// <summary>
  /// Represents a single cell and its value.
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TColumnValue : TBase
  {
    private long _timestamp;
    private byte[] _tags;

    public byte[] Family { get; set; }

    public byte[] Qualifier { get; set; }

    public byte[] Value { get; set; }

    public long Timestamp
    {
      get
      {
        return _timestamp;
      }
      set
      {
        __isset.timestamp = true;
        this._timestamp = value;
      }
    }

    public byte[] Tags
    {
      get
      {
        return _tags;
      }
      set
      {
        __isset.tags = true;
        this._tags = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool timestamp;
      public bool tags;
    }

    public TColumnValue() {
    }

    public TColumnValue(byte[] family, byte[] qualifier, byte[] value) : this() {
      this.Family = family;
      this.Qualifier = qualifier;
      this.Value = value;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_family = false;
        bool isset_qualifier = false;
        bool isset_value = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Family = iprot.ReadBinary();
                isset_family = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Qualifier = iprot.ReadBinary();
                isset_qualifier = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                Value = iprot.ReadBinary();
                isset_value = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I64) {
                Timestamp = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.String) {
                Tags = iprot.ReadBinary();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_family)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Family not set");
        if (!isset_qualifier)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Qualifier not set");
        if (!isset_value)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Value not set");
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TColumnValue");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Family == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Family not set");
        field.Name = "family";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Family);
        oprot.WriteFieldEnd();
        if (Qualifier == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Qualifier not set");
        field.Name = "qualifier";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Qualifier);
        oprot.WriteFieldEnd();
        if (Value == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Value not set");
        field.Name = "value";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Value);
        oprot.WriteFieldEnd();
        if (__isset.timestamp) {
          field.Name = "timestamp";
          field.Type = TType.I64;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(Timestamp);
          oprot.WriteFieldEnd();
        }
        if (Tags != null && __isset.tags) {
          field.Name = "tags";
          field.Type = TType.String;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteBinary(Tags);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TColumnValue(");
      __sb.Append(", Family: ");
      __sb.Append(Family);
      __sb.Append(", Qualifier: ");
      __sb.Append(Qualifier);
      __sb.Append(", Value: ");
      __sb.Append(Value);
      if (__isset.timestamp) {
        __sb.Append(", Timestamp: ");
        __sb.Append(Timestamp);
      }
      if (Tags != null && __isset.tags) {
        __sb.Append(", Tags: ");
        __sb.Append(Tags);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
