/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Apache.Hadoop.Hbase.Thrift2
{

  /// <summary>
  /// Represents a single cell and the amount to increment it by
  /// </summary>
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TColumnIncrement : TBase
  {
    private long _amount;

    public byte[] Family { get; set; }

    public byte[] Qualifier { get; set; }

    public long Amount
    {
      get
      {
        return _amount;
      }
      set
      {
        __isset.amount = true;
        this._amount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool amount;
    }

    public TColumnIncrement() {
      this._amount = 1;
      this.__isset.amount = true;
    }

    public TColumnIncrement(byte[] family, byte[] qualifier) : this() {
      this.Family = family;
      this.Qualifier = qualifier;
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        bool isset_family = false;
        bool isset_qualifier = false;
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Family = iprot.ReadBinary();
                isset_family = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Qualifier = iprot.ReadBinary();
                isset_qualifier = true;
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I64) {
                Amount = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
        if (!isset_family)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Family not set");
        if (!isset_qualifier)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Qualifier not set");
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("TColumnIncrement");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Family == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Family not set");
        field.Name = "family";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Family);
        oprot.WriteFieldEnd();
        if (Qualifier == null)
          throw new TProtocolException(TProtocolException.INVALID_DATA, "required field Qualifier not set");
        field.Name = "qualifier";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Qualifier);
        oprot.WriteFieldEnd();
        if (__isset.amount) {
          field.Name = "amount";
          field.Type = TType.I64;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(Amount);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("TColumnIncrement(");
      __sb.Append(", Family: ");
      __sb.Append(Family);
      __sb.Append(", Qualifier: ");
      __sb.Append(Qualifier);
      if (__isset.amount) {
        __sb.Append(", Amount: ");
        __sb.Append(Amount);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
