/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Apache.Hadoop.Hbase.Thrift2
{
  /// <summary>
  /// Thrift wrapper around
  /// org.apache.hadoop.hbase.filter.CompareFilter$CompareOp.
  /// </summary>
  public enum TCompareOp
  {
    LESS = 0,
    LESS_OR_EQUAL = 1,
    EQUAL = 2,
    NOT_EQUAL = 3,
    GREATER_OR_EQUAL = 4,
    GREATER = 5,
    NO_OP = 6,
  }
}
